<?php

/**
 * @file
 * Install, uninstall and update hooks for VBP text and image module.
 */

use Vardot\Entity\EntityDefinitionUpdateManager;
use Vardot\Installer\ModuleInstallerFactory;

/**
 * Implements hook_install().
 */
function vbp_text_and_image_install() {

  // Processor for install: in vbp_text_and_image.info.yml file.
  ModuleInstallerFactory::installList('vbp_text_and_image');

  // Install optional configs.
  ModuleInstallerFactory::importConfigsFromScanedDirectory('vbp_text_and_image', '/^field.storage.*\\.(yml)$/i');
  ModuleInstallerFactory::importConfigsFromScanedDirectory('vbp_text_and_image', '/^.*(settings.yml)$/i');

  // Add target bundle [text and image] to landing page components
  // (landing page paragraphs field) without changing old configurations.
  _add_target_bundle_text_and_image_to_landing_page_components();

  // Entity updates to clear up any mismatched entity and/or field definitions
  // And Fix changes were detected in the entity type and field definitions.
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EntityDefinitionUpdateManager::class)
    ->applyUpdates();

  // Add permissions.
  ModuleInstallerFactory::addPermissions('vbp_text_and_image');

}

/**
 * Add target bundle [text and image] to landing page components.
 *
 * (landing page paragraphs field) without changing old configurations.
 */
function _add_target_bundle_text_and_image_to_landing_page_components() {
  $site_config = \Drupal::configFactory()->getEditable('field.field.node.landing_page.field_lp_paragraphs');
  $config_data = $site_config->get();

  /* dependencies:
   * config:
   * - paragraphs.paragraphs_type.text_and_image
   */
  if (!isset($config_data['dependencies']['config']['paragraphs.paragraphs_type.text_and_image'])) {
    $config_data['dependencies']['config'][] = 'paragraphs.paragraphs_type.text_and_image';
  }

  /* settings:
   * handler_settings:
   * target_bundles:
   * text_and_image: text_and_image
   */
  if (!isset($config_data['settings']['handler_settings']['target_bundles']['text_and_image'])) {
    $config_data['settings']['handler_settings']['target_bundles']['text_and_image'] = 'text_and_image';
  }

  /* target_bundles_drag_drop
   * text_and_image:
   * enabled: true
   * weight: 32
   */
  if (!isset($config_data['settings']['handler_settings']['target_bundles_drag_drop']['text_and_image'])) {
    $config_data['settings']['handler_settings']['target_bundles_drag_drop']['text_and_image'] = [
      'enabled' => TRUE,
      'weight' => 32,
    ];
  }

  $site_config->setData($config_data)->save(TRUE);

}

// Load include all updates and apply them.
\Drupal::moduleHandler()->loadInclude('vbp_text_and_image', 'inc', 'include/updates/all');
